### ISSUE TITLE
Missing drivers in oneplus/SM8350_S_12.0_9Pro branch

### ISSUE THREAD

**Issue by pjgowtham** [OnePlusOSS/android_kernel_oneplus_sm8350#10]
Kindly upload the missing drivers

https://github.com/OnePlusOSS/android_kernel_oneplus_sm8350/blob/oneplus/SM8350_S_12.0_9Pro/drivers/input/oplus_secure_drivers

https://github.com/OnePlusOSS/android_kernel_oneplus_sm8350/blob/oneplus/SM8350_S_12.0_9Pro/drivers/soc/oplus/midas

**Comment by b1ad3runn3r** [comment]
Yes, upload the drivers mentioned above. Build unavailable due to lack of them
![изображение](https://user-images.githubusercontent.com/31962327/185623369-aa203e8d-6040-448c-8349-54bb571dd7f3.png)

**Comment by CathyKMeow** [comment]
It's in another repo, [https://github.com/OnePlusOSS/android_kernel_modules_and_devicetree_oneplus_sm8350](OnePlusOSS/android_kernel_modules_and_devicetree_oneplus_sm8350).
