### ISSUE TITLE
Missing WLAN drivers in oneplus/SM8350_S_12.0_9Pro branch

### ISSUE THREAD

**Issue by AKoskovich** [OnePlusOSS/android_kernel_oneplus_sm8350#11]
vendor/qcom/opensource/wlan/fw-api
vendor/qcom/opensource/wlan/qca-wifi-host-cmn
vendor/qcom/opensource/wlan/qcacld-3.0

Please upload these to match the SM8450 source drop. Would be greatly appreciated.

**Comment by CathyKMeow** [comment]
They are here, [`OnePlusOSS/android_kernel_modules_and_devicetree_oneplus_sm8350:/vendor/qcom/opensource/wlan/`](https://github.com/OnePlusOSS/android_kernel_modules_and_devicetree_oneplus_sm8350/tree/oneplus/sm8350_s_12.1_op9/vendor/qcom/opensource/wlan).
