### ISSUE TITLE
Request for Oneplus 9 Pro Kernel Source Update

### ISSUE THREAD

**Issue by Oosl** [OnePlusOSS/android_kernel_oneplus_sm8350#20]
Dear Oneplus team,

I'm a proud user of the Oneplus 9 Pro Android phone, and I've been looking to modify and customize its kernel to better suit my needs. In this regard, I've been trying to use the OneplusOSS/android_kernel_oneplus_sm8350 repository as a starting point.

However, I've noticed that the kernel source code provided on this repository is outdated and doesn't match the current kernel version running on my device. As a result, I've been unable to compile and use custom kernels on my device.

Therefore, I would like to request an update to the Oneplus 9 Pro kernel source code on the OneplusOSS/android_kernel_oneplus_sm8350 repository. This would enable me and other users to better customize and optimize our devices for our specific use cases.

Thank you for your attention and consideration. I look forward to hearing back from you soon.

**Comment by Oosl** [comment]
@OnePlusOSSAdmin pls

**Comment by KangHHo** [comment]
@OnePlusOSSAdmin can we please get an update to the OOS 13.1 kernel source for the Oneplus 9 and the Pro version?
