### ISSUE TITLE
Missing separator

### ISSUE THREAD

**Issue by ArtyomKor** [OnePlusOSS/android_kernel_oneplus_sm8350#25]
An error occurs during compilation:
`android_kernel_oneplus_sm8350/arch/arm64/boot/dts/vendor/oplus/lemonadev/Makefile:14: *** Missing separator. Stop.`
How can I fix it?

**Comment by Jun-bit** [comment]
我在编译时也碰到了相同的错误，请问解决了么

**Comment by ArtyomKor** [comment]
不，我正在等待OnePlus的回复

**Comment by Jun-bit** [comment]
我解决了这个问题，第 14 行代码有问题，只需将13行代码变成这样就可以，如下：
dtb-$(CONFIG_ARCH_LAHAINA) += \

**Comment by ArtyomKor** [comment]
谢谢！
